---
title: Flex Example
output:
  flexdashboard::flex_dashboard:
    orientation: columns
    vertical_layout: fill
    self_contained: true
    social: ["twitter","facebook","google"]
    logo: Chancellor50x.bmp
    favicon: icon-blue.png
    source_code: embed
runtime: shiny
---

```{r setup}
knitr::opts_chunk$set(cache = FALSE)
```

```{r load-data,cache=TRUE}
data(economics, package='ggplot2')

```
```{r load-packages, cache=TRUE}
library(ggplot2)
library(magrittr)
library(leaflet)

```
```{r locations}
root <- rprojroot::find_rstudio_root_file()

```

```{r read-map-data}
pizza <- jsonlite::fromJSON(file.path(root, 'FavoriteSpots.json')) %>% 
  tidyr::unnest()
```
```{r read-file}
theData <- reactive(
  {
    if(is.null(input$FileUpload))
    {
      return(NULL)
    }
    
    readr::read_csv(input$FileUpload$datapath)
    
    
  }
)

```

# First Page

## Controls {.sidebar data-width=300}

```{r file-input}
fileInput(
  inputId = 'FileUpload',
  label = 'Please upload a file',
  multiple = FALSE,
  buttonLabel = 'Upload',
  placeholder = 'Waiting for File'
)

```

## Data View {.tabset}

### Table

```{r show-uploaded-data}
DT::renderDataTable((DT::datatable(theData())))

```

### Summary

```{r show-summary}
renderPrint(summary(theData()))

```

# Second Page

## Left

### One

```{r display-econ}
DT::renderDataTable(DT::datatable(economics))

```

### Selector {data-height=250}
```{r hist-var}
selectInput(
  inputId = 'HistVar',
  label = 'Please select a column',
  choices = names(economics)
)

```

## Right

### Top

```{r hist-econ}
renderPlot(ggplot(economics, aes(x=psavert)) + geom_histogram())


```

### Bottom

```{r scatter-econ}
renderPlot(ggplot(economics, aes(x = psavert, y=pce)) + geom_point())
```

# Page Three {data-navmenu="Menu A"}

Manji

# Page Four {data-navmenu="Menu A"}

Snake

# Page Five {data-navmenu="Menu b"}

Lizard

# Page Six {data-navmenu="Menu b"}

Dragon

# Map

##

### Data

```{r pizza-table}
DT::renderDataTable(
  DT::datatable(
    pizza,
    rownames=FALSE,
    options = list(scrollX=TRUE)
  )
)

```

## 

### Map

```{r pizza-map}
renderLeaflet(
    leaflet(pizza) %>%
      addTiles() %>%
      addMarkers(
        lng = ~longitude, lat = ~latitude,
        popup = ~Name
    )
)


```